### ISSUE TITLE
Time limit exceeded on lits challenge

### ISSUE THREAD

**Issue by seddik11** [Confusezius/LiTS_2D_Segmentation_Pipeline#1]
hello,
yesterday i made a submission on codalab but after running a couple of hours i was surprised by a weird ''time limit exceeded" error do you have any idea about the origin of this error ? thank you

**Comment by Confusezius** [comment]
I sometimes got that issue as well, but I got it fixed by resubmitting. It might be a server issue.

**Comment by seddik11** [comment]
@Confusezius Thank you so much
