### ISSUE TITLE
I got some error when training

### ISSUE THREAD

**Issue by ouchaochao** [Confusezius/LiTS_2D_Segmentation_Pipeline#3]
When running

```python Train_Networks/Train_Networks.py --search_setup Small_UNet_Liver.txt --no_date```

i got this errror, and dont know how to fix it.

```
Setup Iteration... :   0%|                                                                    | 0/1 [00:00<?, ?it/s]│
Traceback (most recent call last):                                                                                 
  File "Train_Networks/Train_Networks.py", line 232, in <module>                                                    
    main(training_setup)                                                                                           
  File "Train_Networks/Train_Networks.py", line 114, in main                                                        
    train_dataset, val_dataset = Data.Generate_Required_Datasets(opt)                                               
  File "/home/cc/jupyter/unet-lits-2d-pipeline/Train_Networks/../Utilities/PyTorch_Datasets.py", line 23, in Generat
e_Required_Datasets                                                                                                 
    available_volumes = sorted(list(set(np.array(vol_info['volume_slice_info']['Volume']))), key=lambda x: int(x.spl
it('-')[-1]))                                                                                                      
  File "/home/cc/jupyter/unet-lits-2d-pipeline/Train_Networks/../Utilities/PyTorch_Datasets.py", line 23, in <lambda                                                                                   
    available_volumes = sorted(list(set(np.array(vol_info['volume_slice_info']['Volume']))), key=lambda x: int(x.spl
it('-')[-1]))                                                                                                       
ValueError: invalid literal for int() with base 10: 'Volume'  
```

Could u please help me?

**Comment by Confusezius** [comment]
Can you tell my how you store the volumes? I.e. what are the folder-names?

This looks like a wrong splitting of a string, where the result can't be converted to an integer.

What happens in the line that causes the problems is the following:
All available volume names are stored in a list by running `list(set(np.array(vol_info['volume_slice_info']['Volume'])))`. Assuming that the volumes are stored under e.g. 'Volume-X', where the indicating number is required to come last, each string in the list is split along '-', and string number 'X' is then converted to an integer for sorting.

The error already tells that the name of your volume folders must have a different structure, where 'Volume' comes last, i.e. something like 'XXX-YYY-Volume'. Splitting along '-' and taking the last element will then return the string 'Volume' which can't be converted to an integer.

See also Section [3.] - (1.) in the README to see how the folders should be named.

**Comment by Confusezius** [comment]
I will close this for now - feel free to reopen if my suggestion did not solve your problem.
